baseURL = "https://dgdavid.github.io/website"
languageCode = "en"
title = "David Díaz's blog"
publishDir = "docs"
theme = "kiss"
enableEmoji = true

[params.assets]
customCSS = ["css/custom.css"]

[params.social]
github = "dgdavid"
linkedin = "diazglezdavid"
twitter = "diazglezdavid"

[params.sections_right]
"/website/hi-there/" = "About me"

[blackfriday]
hrefTargetBlank = true
